using CalculatorSuite.Controls; using CalculatorSuite.Services; using System.Drawing.Imaging; using ZXing; using ZXing.Common; using PdfiumViewer;
namespace CalculatorSuite;
public class DashboardControl:UserControl{public DashboardControl(MainForm m){BackColor=Ui.Bg;var f=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,WrapContents=true,Padding=new Padding(0,30,0,20)};Add(f,"Age Calculator","Precise years, months, days, weeks, hours and seconds.",()=>m.Go("Age Calculator"));Add(f,"Pakistan Salaried Tax","Historical salary tax slabs from the supplied HTML code.",()=>m.Go("Salaried Tax"));Add(f,"Pakistan Business Tax","FBR business/non-salaried calculation and surcharge.",()=>m.Go("Business Tax"));Add(f,"Loan EMI","EMI, interest breakdown and year-wise amortization.",()=>m.Go("Loan EMI"));Add(f,"Code 39","Generate and save Code 39 barcodes.",()=>m.Go("Code 39"));Add(f,"PDF417","Generate PDF417 barcodes with adjustable settings.",()=>m.Go("PDF417"));Add(f,"PDF to Image","Render PDF pages to PNG images.",()=>m.Go("PDF to Image"));Controls.Add(f);}void Add(FlowLayoutPanel f,string t,string d,Action a){var p=new Panel{Width=330,Height=210,BackColor=Color.White,Margin=new Padding(10)};p.Paint+=(s,e)=>{using var pen=new Pen(Ui.Border);e.Graphics.DrawRectangle(pen,0,0,p.Width-1,p.Height-1);};var l=new Label{Text=t,Font=Ui.H2,ForeColor=Ui.Text,AutoSize=false,Width=290,Height=32,Location=new Point(20,30)};var x=new Label{Text=d,Font=Ui.Small,ForeColor=Ui.Muted,AutoSize=false,Width=290,Height=50,Location=new Point(20,70)};var b=Ui.Button("Open Tool");b.Top=140;b.Left=20;b.Click+=(s,e)=>a();p.Controls.AddRange([l,x,b]);l.BringToFront();f.Controls.Add(p);}}

public class AgeControl:UserControl{DateTimePicker dob=new(){Format=DateTimePickerFormat.Short};DateTimePicker target=new(){Format=DateTimePickerFormat.Short,Value=DateTime.Today};Label result=new(){Font=new Font("Segoe UI",16,FontStyle.Bold),ForeColor=Ui.Blue,AutoSize=true};public AgeControl(){var p=Ui.Card("Age Calculator");p.Controls.Add(Ui.Label("Date of Birth"));dob.Top=75;dob.Width=240;p.Controls.Add(dob);var l=Ui.Label("Age at the Date of");l.Top=125;p.Controls.Add(l);target.Top=155;target.Width=240;p.Controls.Add(target);var b=Ui.Button("Calculate");b.Top=205;b.Click+=(_,_)=>Calc();p.Controls.Add(b);result.Top=270;p.Controls.Add(result);Controls.Add(p);}void Calc(){if(target.Value.Date<dob.Value.Date){MessageBox.Show("Target date cannot be earlier than birth date.");return;}var inclusiveTarget=target.Value.Date.AddDays(1);var y=inclusiveTarget.Year-dob.Value.Year;var m=inclusiveTarget.Month-dob.Value.Month;var d=inclusiveTarget.Day-dob.Value.Day;if(d<0){m--;var previousMonth=inclusiveTarget.Month==1?12:inclusiveTarget.Month-1;var previousYear=inclusiveTarget.Month==1?inclusiveTarget.Year-1:inclusiveTarget.Year;d+=DateTime.DaysInMonth(previousYear,previousMonth);}if(m<0){y--;m+=12;}var days=(inclusiveTarget-dob.Value.Date).Days;result.Text=$"Age: {y} years {m} months {d} days\n{days:N0} days  •  {days/7:N0} weeks  •  {(days*24):N0} hours";}}

public class SalariedTaxControl:UserControl
{
 TextBox monthly=new(){PlaceholderText="Enter Monthly",Width=300};
 TextBox annual=new(){PlaceholderText="Total Annual",Width=300,ReadOnly=true,BackColor=Color.White};
 ComboBox year=Ui.Combo("2026 - 2027","2025 - 2026","2024 - 2025","2023 - 2024","2022 - 2023","2021 - 2022","2020 - 2021","2019 - 2020","2018 - 2019","2017 - 2018","2016 - 2017","2015 - 2016");
 Label outp=new(){AutoSize=true,Font=new Font("Segoe UI",18,FontStyle.Bold),ForeColor=Color.FromArgb(217,83,79)};
 public SalariedTaxControl()
 {
  var p=Ui.Card("Salaried Tax Calculator");
  AddLabel(p,"Monthly Salary (PKR)",45);monthly.Top=68;monthly.Left=22;p.Controls.Add(monthly);
  AddLabel(p,"Annual Salary (PKR)",115);annual.Top=138;annual.Left=22;p.Controls.Add(annual);
  AddLabel(p,"Tax Year",185);year.Top=208;year.Left=22;year.Width=300;p.Controls.Add(year);
  var b=Ui.Button("Calculate Tax");b.Top=265;b.Left=22;b.Width=300;b.Click+=(_,_)=>Calculate();p.Controls.Add(b);
  monthly.TextChanged+=(_,_)=>UpdateAnnual();outp.Top=330;outp.Left=22;p.Controls.Add(outp);Controls.Add(p);
 }
 void AddLabel(Control parent,string text,int top){var label=Ui.Label(text);label.Top=top;label.Left=22;parent.Controls.Add(label);}
 void UpdateAnnual(){if(decimal.TryParse(monthly.Text.Replace(",",""),out var value))annual.Text=(value*12).ToString("N0");else annual.Clear();}
 void Calculate(){if(!decimal.TryParse(annual.Text.Replace(",",""),out var income)||income<=0){outp.Text="Enter a valid monthly salary.";return;}var tax=TaxService.Salaried(income,year.Text[..4]);outp.Text=$"Annual Tax: Rs. {Math.Round(tax):N0}\nMonthly Tax: Rs. {Math.Round(tax/12):N0}";}
}

public class BusinessTaxControl:UserControl{NumericUpDown income=new(){Maximum=1000000000,ThousandsSeparator=true,DecimalPlaces=0,Increment=10000};ComboBox year=Ui.Combo("2027","2026","2025","2024","2023");Label outp=new(){AutoSize=true,Font=new Font("Segoe UI",18,FontStyle.Bold),ForeColor=Color.FromArgb(40,167,69)};Label note=new(){AutoSize=false,Width=700,Height=60,Top=325,ForeColor=Ui.Muted};public BusinessTaxControl(){var p=Ui.Card("Pakistan FBR Business Tax Calculator");p.Controls.Add(Ui.Label("Annual Taxable Income (PKR)"));income.Top=75;income.Width=300;p.Controls.Add(income);var l=Ui.Label("Tax Year");l.Top=125;p.Controls.Add(l);year.Top=155;year.Width=300;p.Controls.Add(year);var b=Ui.Button("Calculate Tax");b.Top=205;b.Click+=(_,_)=>{var r=TaxService.Business(income.Value,year.Text);outp.Text=$"Estimated Tax: Rs. {Math.Round(r.Tax):N0}";note.Text=r.Note;};p.Controls.Add(b);outp.Top=275;p.Controls.Add(outp);p.Controls.Add(note);Controls.Add(p);}}

public class LoanControl:UserControl{NumericUpDown principal=new(){Maximum=1000000000,ThousandsSeparator=true,DecimalPlaces=0,Increment=10000,Value=1000000};NumericUpDown rate=new(){Maximum=100,DecimalPlaces=2,Increment=.25m,Value=10};NumericUpDown tenure=new(){Maximum=50,DecimalPlaces=0,Value=5};ComboBox unit=Ui.Combo("Years","Months");Label emi=new(){AutoSize=true,Font=new Font("Segoe UI",22,FontStyle.Bold),ForeColor=Ui.Blue};DataGridView grid=new(){Dock=DockStyle.Fill,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,ReadOnly=true,AllowUserToAddRows=false,BackgroundColor=Color.White};public LoanControl(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=2};root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,40));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,60));root.RowStyles.Add(new RowStyle(SizeType.Absolute,340));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));var p=Ui.Card("Loan EMI Calculator");Add(p,"Loan Amount (PKR)",principal,65);Add(p,"Annual Interest Rate (%)",rate,110);Add(p,"Tenure",tenure,155);unit.Top=155;unit.Left=330;unit.Width=110;unit.SelectedIndexChanged+=(_,_)=>Calc();p.Controls.Add(unit);var b=Ui.Button("Calculate");b.Top=205;b.Click+=(_,_)=>Calc();p.Controls.Add(b);emi.Top=245;p.Controls.Add(emi);var right=Ui.Card("Year-wise Amortization Schedule");right.Controls.Add(grid);root.Controls.Add(p,0,0);root.Controls.Add(right,0,1);root.SetColumnSpan(right,2);Controls.Add(root);Calc();}void Add(Control p,string s,Control c,int top){var l=Ui.Label(s);l.Top=top;l.Left=22;p.Controls.Add(l);c.Top=top+22;c.Left=22;c.Width=280;p.Controls.Add(c);}void Calc(){double P=(double)principal.Value,r=(double)rate.Value/1200;int months=(int)tenure.Value*(unit.Text=="Years"?12:1);if(P<=0||months<=0)return;double e=r==0?P/months:P*r*Math.Pow(1+r,months)/(Math.Pow(1+r,months)-1);emi.Text=$"Monthly EMI: PKR {e:N2}";grid.Columns.Clear();grid.Columns.Add("Period",unit.Text=="Months"?"Month":"Year");grid.Columns.Add("Principal","Principal Paid");grid.Columns.Add("Interest","Interest Paid");grid.Columns.Add("Payment","Total Payment");grid.Columns.Add("Balance","Remaining Balance");grid.Rows.Clear();double bal=P,yp=0,yi=0;int yr=1;for(int m=1;m<=months;m++){double interest=bal*r;double pp=Math.Min(e-interest,bal);bal=Math.Max(0,bal-pp);if(unit.Text=="Months"){grid.Rows.Add($"Month {m}",pp.ToString("N2"),interest.ToString("N2"),e.ToString("N2"),bal.ToString("N2"));}else{yp+=pp;yi+=interest;if(m%12==0||m==months){grid.Rows.Add($"Year {yr++}",yp.ToString("N2"),yi.ToString("N2"),(yp+yi).ToString("N2"),bal.ToString("N2"));yp=yi=0;}}}}}
